- added run wrapper - added logging - activated picasa upload

diff --git a/bash/graphics/upload-to-picasa b/bash/graphics/upload-to-picasa
--- a/bash/graphics/upload-to-picasa
+++ b/bash/graphics/upload-to-picasa
@@ -6,6 +6,21 @@
 
 state_file=$HOME/.$(basename $0).state
 lock_file=/tmp/$(basename $0).lock
+log_file=/tmp/$(basename $0).log
+
+function log() {
+  echo "$@" >> $log_file
+}
+
+function run() {
+  "$@" >> $log_file 2>> $log_file
+  
+  if [ $? -gt 0 ]; then
+    log "The command [ $@ ] failed :-( Exiting."
+    rm lock_file
+    exit 1
+  fi
+}
 
 function create_lock_or_exit_if_exists() {
   if [ -e $lock_file ]; then
@@ -19,7 +34,7 @@ function create_lock_or_exit_if_exists() {
 ## $1: file
 function upload_to_picasa() {
   if [ $(grep $1 $state_file 2>/dev/null | wc -l) -gt 0 ]; then
-    echo $1 "already uploaded to picasa"
+    log $1 "already uploaded to picasa"
     return
   fi
 
@@ -30,7 +45,7 @@ function upload_to_picasa() {
   )
   
   local album_name=$(date --date=$file_date "+%B %Y")
-  echo google post \"$album_name\" $1
+  run google post \"$album_name\" $1
   echo $1 >> $state_file
 }
 
