Added getopt parsing to cmd template

diff --git a/emacs/.emacs.d/snippets/sh-mode/cmd b/emacs/.emacs.d/snippets/sh-mode/cmd
--- a/emacs/.emacs.d/snippets/sh-mode/cmd
+++ b/emacs/.emacs.d/snippets/sh-mode/cmd
@@ -13,7 +13,36 @@ source ~/src/moria/src/common/indispensable.sh
 source ~/src/moria/src/common/common-exit-hook.sh
 
 read_user_input() {
-  :
+  local OPTS=
+  OPTS=$(getopt \
+           -o hc: \
+           --long help \
+           --long conf: \
+           -n 'parse-options' \
+           -- "$@")
+  if [ $? != 0 ] ; then
+    echo "Failed parsing options." >&2
+    exit 1
+  fi
+  eval set -- "$OPTS"
+
+  while true; do
+    case "$1" in
+      -c | --conf )
+        conf_file="$2";
+        shift 2;;
+      -h | --help )
+        show_help_and_exit;
+        break;;
+      -- )
+        shift;
+        break ;;
+      * )
+        break ;;
+    esac
+  done
+
+  rest_of_args=$*
 }
 
 main() {
